optimize build pipelines

diff --git a/.github/workflows/backwards-compatibility.yml b/.github/workflows/backwards-compatibility.yml
--- a/.github/workflows/backwards-compatibility.yml
+++ b/.github/workflows/backwards-compatibility.yml
@@ -2,7 +2,7 @@ name: Backwards Compatibility
 
 on:
   push:
-    branches: [ develop ]
+    branches: [develop]
     paths:
       - "core-customize/hybris/bin/custom/sapcxtools/**/*.java"
       - "core-customize/hybris/bin/custom/sapcxtools/**/*-beans.xml"
@@ -10,66 +10,66 @@ on:
       - "core-customize/hybris/bin/custom/sapcxtools/**/extensioninfo.xml"
       - "core-customize/hybris/bin/custom/sapcxtools/**/external-dependencies.xml"
   pull_request:
-    branches: [ main, develop ]
+    branches: [main, develop]
   schedule:
-    - cron: '0 15 * * 0,3'
+    - cron: "0 15 * * 0,3"
 
 jobs:
-  build:
+  compatibility:
     runs-on: ubuntu-latest
     strategy:
       fail-fast: false
       matrix:
-        version: ['2011.19', '2005.23']
+        version: ["2011.19", "2005.23"]
     steps:
-    - uses: actions/checkout@v2
-    - name: Set up JDK 11
-      uses: actions/setup-java@v2
-      with:
-        distribution: 'temurin'
-        java-version: '11'
-        cache: 'gradle'
-    - name: Validate Gradle wrapper
-      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
-    - name: Set up cache for SAP artifacts
-      uses: actions/cache@v2
-      with:
-        key: sap-artifacts-cache-${{ hashFiles('core-customize/manifest.json') }}-${{ matrix.version }}
-        path: dependencies
-    - name: Configure SAP version
-      run: |
-        sed -i 's/\"commerceSuiteVersion\": \"[^\"]*\"/\"commerceSuiteVersion\": \"${{ matrix.version }}\"/' core-customize/manifest.json
-    - name: SAP download config
-      env:
-        USER_CONFIG: ${{ secrets.GRADLE_USER_CONFIG }}
-        AUTHORIZATION: ${{ secrets.SAP_DOWNLOAD_AUTHORIZATION }}
-      shell: bash
-      run: |
-        mkdir -p ${HOME}/.gradle
-        echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
-        echo "${USER_CONFIG}" >> ${HOME}/.gradle/gradle.properties
-        echo "sUserAuthorization=${AUTHORIZATION}" >> ${HOME}/.gradle/gradle.properties
-    - name: SAP Commerce environment
-      run: |
-        echo "HYBRIS_OPT_CONFIG_DIR=$GITHUB_WORKSPACE/core-customize/hybris/config/local-config" >> $GITHUB_ENV
-        echo "HYBRIS_BIN_DIR=$GITHUB_WORKSPACE/core-customize/hybris/bin" >> $GITHUB_ENV
-        echo "HYBRIS_CONF_DIR=$GITHUB_WORKSPACE/core-customize/hybris/config" >> $GITHUB_ENV
-        echo "HYBRIS_LOG_DIR=$GITHUB_WORKSPACE/core-customize/hybris/log" >> $GITHUB_ENV
-    - name: Bootstrap platform
-      run: ./gradlew setupLocalDevelopment
-    - name: Build platform
-      run: ./gradlew yall
-    - name: Run unit tests
-      run: |
-        cat $GITHUB_WORKSPACE/ci/config/testing-unit.properties > $HYBRIS_CONF_DIR/local-config/99-local.properties
-        ./gradlew yunittests
-        
-        # Target never fails, therefore, check for test errors and fail if errors were found
-        for file in $HYBRIS_LOG_DIR/junit/test-results/unit/*.xml; do if [ "$(grep -cE '<(error|failure)' "${file}")" -gt 0 ]; then exit 1; fi; done
-    - name: Run integration tests
-      run: |
-        cat $GITHUB_WORKSPACE/ci/config/testing-integration.properties > $HYBRIS_CONF_DIR/local-config/99-local.properties
-        ./gradlew yintegrationtests
-        
-        # Target never fails, therefore, check for test errors and fail if errors were found
-        for file in $HYBRIS_LOG_DIR/junit/test-results/integration/*.xml; do if [ "$(grep -cE '<(error|failure)' "${file}")" -gt 0 ]; then exit 1; fi; done
+      - uses: actions/checkout@v2
+      - name: Set up JDK 11
+        uses: actions/setup-java@v2
+        with:
+          distribution: "temurin"
+          java-version: "11"
+          cache: "gradle"
+      - name: Validate Gradle wrapper
+        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
+      - name: Set up cache for SAP artifacts
+        uses: actions/cache@v2
+        with:
+          key: sap-artifacts-cache-${{ hashFiles('core-customize/manifest.json') }}-${{ matrix.version }}
+          path: dependencies
+      - name: Configure SAP version
+        run: |
+          sed -i 's/\"commerceSuiteVersion\": \"[^\"]*\"/\"commerceSuiteVersion\": \"${{ matrix.version }}\"/' core-customize/manifest.json
+      - name: SAP download config
+        env:
+          USER_CONFIG: ${{ secrets.GRADLE_USER_CONFIG }}
+          AUTHORIZATION: ${{ secrets.SAP_DOWNLOAD_AUTHORIZATION }}
+        shell: bash
+        run: |
+          mkdir -p ${HOME}/.gradle
+          echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
+          echo "${USER_CONFIG}" >> ${HOME}/.gradle/gradle.properties
+          echo "sUserAuthorization=${AUTHORIZATION}" >> ${HOME}/.gradle/gradle.properties
+      - name: SAP Commerce environment
+        run: |
+          echo "HYBRIS_OPT_CONFIG_DIR=$GITHUB_WORKSPACE/core-customize/hybris/config/local-config" >> $GITHUB_ENV
+          echo "HYBRIS_BIN_DIR=$GITHUB_WORKSPACE/core-customize/hybris/bin" >> $GITHUB_ENV
+          echo "HYBRIS_CONF_DIR=$GITHUB_WORKSPACE/core-customize/hybris/config" >> $GITHUB_ENV
+          echo "HYBRIS_LOG_DIR=$GITHUB_WORKSPACE/core-customize/hybris/log" >> $GITHUB_ENV
+      - name: Bootstrap platform
+        run: ./gradlew setupLocalDevelopment
+      - name: Build platform
+        run: ./gradlew yall
+      - name: Run unit tests
+        run: |
+          cat $GITHUB_WORKSPACE/ci/config/testing-unit.properties > $HYBRIS_CONF_DIR/local-config/99-local.properties
+          ./gradlew yunittests
+
+          # Target never fails, therefore, check for test errors and fail if errors were found
+          for file in $HYBRIS_LOG_DIR/junit/test-results/unit/*.xml; do if [ "$(grep -cE '<(error|failure)' "${file}")" -gt 0 ]; then exit 1; fi; done
+      - name: Run integration tests
+        run: |
+          cat $GITHUB_WORKSPACE/ci/config/testing-integration.properties > $HYBRIS_CONF_DIR/local-config/99-local.properties
+          ./gradlew yintegrationtests
+
+          # Target never fails, therefore, check for test errors and fail if errors were found
+          for file in $HYBRIS_LOG_DIR/junit/test-results/integration/*.xml; do if [ "$(grep -cE '<(error|failure)' "${file}")" -gt 0 ]; then exit 1; fi; done
